// AUTO-GENERATED by scripts/build-config-inject. Do not edit.
export interface BuildConfig {
  companyId: string;
  displayName: string;
  builtAt: string;
}

export const BUILD_CONFIG: BuildConfig = {
  companyId: 'chigasaki-tokushukai',
  displayName: '茅ヶ崎徳洲会病院 Scout (WelMe)',
  builtAt: '2026-04-21T04:31:05.075Z',
};
